services:
  bot:
    build:
      context: .
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
    networks:
      - net
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - 8501:8501
networks:
  net:
