apiVersion: apps/v1
kind: Deployment
metadata:
  name: keynote
  labels:
    app: keynote
spec:
  replicas: 1 # Specifies the number of instances
  selector:
    matchLabels:
      app: keynote
  template:
    metadata:
      labels:
        app: keynote
    spec:
      containers:
        - name: keynote
          image: ghcr.io/cncf/keynote
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: OLLAMA_BASE_URL
              value: "http://host.docker.internal:11434"
