apiVersion: apps/v1
kind: Deployment
metadata:
  name: keynote
  labels:
    app: keynote
spec:
  replicas: 1 # Specifies the number of instances
  selector:
    matchLabels:
      app: keynote
  template:
    metadata:
      labels:
        app: keynote
    spec:
      volumes:
        - name: keynote-pvc
          persistentVolumeClaim:
            claimName: keynote-pvc
      containers:
        - name: keynote
          #          image: ghcr.io/cncf/keynote
          image: quay.io/rhn_support_arolivei/keynote:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/tmp"
              name: keynote-pvc
          ports:
            - containerPort: 8501
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama-svc.ollama.svc.cluster.local"
